version: "3.8"

services:
  postgresql:
    image: 'postgres:15.4-alpine'
    environment:
      - 'POSTGRES_DB=maindb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./project
    entrypoint:
      [
        "java",
        "-jar",
        "-Dspring.profiles.active=compose",
        "app.jar"
      ]
    ports:
      - 8080:8080
    depends_on:
      - postgresql

volumes:
  pg_data:
