apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybackend-deplo
  labels:
    app: myapp
    type: backend

spec:
  template:
    metadata:
      labels:
        app: myapp
        type: backend
    spec:
      containers:
        - name: mybackend-container
          image: xkuklix/projekt_aut
          ports:
          - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      type: backend
